language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wifiscan
  - PLATFORMIO_PROJECT_DIR=examples/espidf-arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/espidf-arduino-wifiscan
  - PLATFORMIO_PROJECT_DIR=examples/espidf-ble-adv
  - PLATFORMIO_PROJECT_DIR=examples/espidf-coap-server
  - PLATFORMIO_PROJECT_DIR=examples/espidf-exceptions
  - PLATFORMIO_PROJECT_DIR=examples/espidf-http-request
  - PLATFORMIO_PROJECT_DIR=examples/espidf-peripherals-uart
  - PLATFORMIO_PROJECT_DIR=examples/espidf-storage-sdcard
  - PLATFORMIO_PROJECT_DIR=examples/pumbaa-blink
  - PLATFORMIO_PROJECT_DIR=examples/simba-blink

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
